"""empty message

Revision ID: 481c41798891
Revises: 
Create Date: 2020-01-26 01:31:02.318485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481c41798891'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(length=280), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_author'), 'chat_messages', ['author'], unique=False)
    op.create_table('current_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('time', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=15), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('hosts', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_hosts'), 'program', ['hosts'], unique=False)
    op.create_index(op.f('ix_program_title'), 'program', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_title'), table_name='program')
    op.drop_index(op.f('ix_program_hosts'), table_name='program')
    op.drop_table('program')
    op.drop_table('current_program')
    op.drop_index(op.f('ix_chat_messages_author'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('broadcast')
    # ### end Alembic commands ###
