"""empty message

Revision ID: b5cfac922a3a
Revises: b4fe544e104c
Create Date: 2020-01-25 23:24:03.752320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cfac922a3a'
down_revision = 'b4fe544e104c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=15), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('hosts', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_hosts'), 'program', ['hosts'], unique=False)
    op.create_index(op.f('ix_program_title'), 'program', ['title'], unique=False)
    op.drop_index('ix_schedule_guests', table_name='schedule')
    op.drop_index('ix_schedule_title', table_name='schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=140), nullable=True),
    sa.Column('guests', sa.VARCHAR(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedule_title', 'schedule', ['title'], unique=False)
    op.create_index('ix_schedule_guests', 'schedule', ['guests'], unique=False)
    op.drop_index(op.f('ix_program_title'), table_name='program')
    op.drop_index(op.f('ix_program_hosts'), table_name='program')
    op.drop_table('program')
    # ### end Alembic commands ###
